### ISSUE TITLE
Dates in Hungarian end with a full stop `.` Can the date format please be added?

### ISSUE THREAD

**Issue by ovari** [alexkdeveloper/easter#12]
In Hungarian, `április 17` should be `április 17.` The `17` should be followed by a full stop `17.`.

Can the date format please be added?

![kép](https://user-images.githubusercontent.com/17465872/173182597-14721df0-7238-4424-899d-de0f58021884.png)

Thank you

**Comment by alexkdeveloper** [comment]
It makes sense to take into account the date format if the full date is specified using separators. For example for Spain: dd/MM/yyyy
Or for Germany: dd.MM.yyyy
For Bulgaria, the following format is used: yyyy-M-d
My app only displays the name of the month and the number of the day in that month. I think that in this case it is absolutely not necessary to use date formatting.

**Comment by ovari** [comment]
Closing as won't fix. Thank you
