### ISSUE TITLE
Italian language does not work

### ISSUE THREAD

**Issue by albanobattistella** [alexkdeveloper/easter#4]
Hi,

Installed the last version, but the language does not work.

**Comment by alexkdeveloper** [comment]
Hi!
I have updated the app. The update will be available soon. Everything should work.

**Comment by albanobattistella** [comment]
> Hi! I have updated the app. The update will be available soon. Everything should work.

Hi,
with the last update the language is fine but remains in English: "Do you want to vist wikipedia?"

**Comment by alexkdeveloper** [comment]
The line "Do you want to visit Wikipedia?" it was not found in the it.po file, so it has not been translated.
