### ISSUE TITLE
English showing instead of Hungarian

### ISSUE THREAD

**Issue by ovari** [alexkdeveloper/easter#8]
Hungarian locale incorrectly shows English strings:
1. `Date of Catholic Easter` in the application window title
2. `Message` in the dialog window title
3. `Enter the year number` string in the dialog window title
4. `OK` button in the dialog window title

![kép](https://user-images.githubusercontent.com/17465872/172952901-dddf6848-42a0-4e55-8b67-535f4bbb377d.png)

Can this please be fixed?

Thank you

Linux Mint 20.3 Cinnamon

**Comment by ovari** [comment]
1. `Question`
2. `Do you want to visit Wikipedia?`
3. `OK`


![kép](https://user-images.githubusercontent.com/17465872/172953333-c5076a41-6cda-408f-b643-3bb4dc5ac795.png)

**Comment by ovari** [comment]
The date format is `American English`, i.e. `MMMM dd` (`April 17`); not `Hungarian`, i.e. `MMMM d.` (`április 17.`). Can your program please obtain the date format from the system?

![kép](https://user-images.githubusercontent.com/17465872/172953488-28b9a7d5-a271-4e26-8766-ffe49588fd5e.png)

What do you think?

Thank you

**Comment by alexkdeveloper** [comment]
The hu.po file is missing lines from window.vala.
The window title is specified in window.ui but is not specified in hu.po, so it is not translated. You need to specify all the necessary lines in the po file, then everything should work. 
The name of the developer (Alex Kryuchkov) is usually not translated into other languages. The name of the month is also present in window.vala. These lines will need to be included in hu.po.
The lines to be translated in window.vala must be enclosed in parentheses with an underscore in front:
`var dialog = new Granite.MessageDialog.with_image_from_icon_name (_("Message"), str, "dialog-warning");`

**Comment by ovari** [comment]
The translations were provided using a web browser.

Sorry, don't understand how to do what you wrote.

Can you please update the code so we can provided the Hungarian translations?

Thank you

**Comment by alexkdeveloper** [comment]
I have updated the window.vala file.
Now it is ready for translation. You can use the Poedit program to create a po file. Here is the link to the program's website:
https://poedit.net/download
The site for Linux offers to download snap, so here is a link to Flathub:
https://flathub.org/apps/details/net.poedit.Poedit
Using this translation editor is quite simple. I think you can easily cope with this task.

**Comment by ovari** [comment]
Thanks for updating.

Could you please add the strings to the `hu.po` file with blank translations? i.e. `msgstr ""`

Then we could type the Hungarian translations into GitHub using our web browser.

Thank you

**Comment by alexkdeveloper** [comment]
Updated the file.
You could do it yourself if you used the software I specified.

**Comment by ovari** [comment]
> You could do it yourself if you used the software I specified.

Installed the software; however, didn't know how to add the file. Sorry.
